//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkalochkinFedor_ISP321_MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int IDAddress { get; set; }
        public int PostIndexID { get; set; }
        public int RegionID { get; set; }
        public int CityID { get; set; }
        public int StreetID { get; set; }
        public int House { get; set; }
    
        public virtual City City { get; set; }
        public virtual PostIndex PostIndex { get; set; }
        public virtual Region Region { get; set; }
        public virtual Street Street { get; set; }
    }
}
