//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkalochkinFedor_ISP321_MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTypeImport
    {
        public int IDMaterialType { get; set; }
        public string MaterialType { get; set; }
        public double PercentDeffect { get; set; }
    }
}
