//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkalochkinFedor_ISP321_MasterFloor.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkalochkinFedor_ISP321_MasterFloorEntities1 : DbContext
    {
        public SkalochkinFedor_ISP321_MasterFloorEntities1()
            : base("name=SkalochkinFedor_ISP321_MasterFloorEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<MaterialTypeImport> MaterialTypeImport { get; set; }
        public virtual DbSet<PartnerProductsImport> PartnerProductsImport { get; set; }
        public virtual DbSet<PartnersImport> PartnersImport { get; set; }
        public virtual DbSet<PartnerType> PartnerType { get; set; }
        public virtual DbSet<PostIndex> PostIndex { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductsImport> ProductsImport { get; set; }
        public virtual DbSet<ProductTypeImport> ProductTypeImport { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TitlePartner> TitlePartner { get; set; }
    }
}
