//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkalochkinFedor_ISP321_MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersImport
    {
        public int IDPartnerImport { get; set; }
        public int TypePartnerID { get; set; }
        public int TitlePartnerID { get; set; }
        public string Female { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int AddressID { get; set; }
        public long INN { get; set; }
        public int Rate { get; set; }
    
        public virtual PostIndex PostIndex { get; set; }
        public virtual TitlePartner TitlePartner { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
