//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkalochkinFedor_ISP321_MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProductsImport
    {
        public int PartnerProductID { get; set; }
        public int ProductID { get; set; }
        public int PartnerTitleID { get; set; }
        public long CountProduct { get; set; }
        public System.DateTime DateSaller { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TitlePartner TitlePartner { get; set; }
    }
}
