//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkalochkinFedor_ISP321_MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsImport
    {
        public int IDProductImport { get; set; }
        public int TypeProductID { get; set; }
        public int TitleProductID { get; set; }
        public long Article { get; set; }
        public double MinPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductTypeImport ProductTypeImport { get; set; }
    }
}
